### ISSUE TITLE
No funciona en 6M62 (osx)

### ISSUE THREAD

**Issue by saimonmoore** [sarganar/I7-2014-Spanish#13]
Acabo de instalarlo en 6M62 (osx) y con el siguiente codigo me da este error:

**Codigo**:

    "Drakoulino" by Saimon Moore (in Spanish)

    The story headline is "Un breve cuento interactivo".

    Draco's Cave is a room. "Una cueva enorme donde el eco de tu voz desaparece en la profunda oscuridad".

**Error**:
    Problem. I can't find the extension 'Spanish Language by Sebastian Arg', which seems not to be installed, but was requested by: 'Include Spanish Language by Sebastian Arg' .

Sin embargo en extensions:

<img width="572" alt="screen shot 2016-05-05 at 23 19 29" src="https://cloud.githubusercontent.com/assets/494/15057593/d9d54ef4-1317-11e6-8199-e5465ab5762f.png">

**Comment by sarganar** [comment]
Hola! Tu extension Spanish al parecer es viejuna (deberia llamarse Spanish Language). Dejame ver si en unas horas subo la que compila con 6M.
Tienes la que compila con 6L en la pestaña **Releases**.

**Comment by saimonmoore** [comment]
Genial @sarganar . Voy a probar 6L. Muchísimas gracias por responder tan rápido.

**Comment by saimonmoore** [comment]
Parece que funciona ahora en 6L (Aunque peto un par de veces al instalar la extension y al arrancarlo: https://gist.github.com/saimonmoore/99f936cc95e5b24ef159fbb203156025).

Ahora parece estable. Luego miraré de probar la version para 6M cuando lo hayas subido. 

Muchas gracias

**Comment by sarganar** [comment]
Ya puedes probar la 6M. No soy usuario manzanero, solo win  
:-(

**Comment by saimonmoore** [comment]
Genial. Funciona perfecta Sebas...Muchas gracias...

**Comment by sarganar** [comment]
Genial! También tienes el [foro del caad](http://foro.caad.es/viewforum.php?f=12), que concentra a toda la peña con dudas.
